server-host: 127.0.0.1
server-port: 19150
debug-mode: true
database-host: 127.0.0.1
database-user: chicken
database-password: 123456
database-name: chicken3
reward-daily-gold: 5000
reward-daily-gem: 10
event-rotation-minutes: 90
event-duration-minutes: 30
world-treasure-spawn-minutes: 8
world-boss-hp: 50000
clan-create-cost-gold: 500000
lucky-wheel-gem-cost: 5
client-version-big: 0
client-version-data: 3
client-version-item: 4
client-version-map: 5
